[package]
name = "reqwest_dll"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "reqwest"

[dependencies]
libc = "0.2.146"
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4.0"
futures-util = "0.3.31"

